<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml">
			<head>
				<title>XML Sitemap</title>
				<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
				<style type="text/css">
					body {
						font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
						background-color: #f8f9fa;
						color: #333;
					}
					#sitemap {
						max-width: 900px;
						margin: 2rem auto;
						background: #fff;
						border-radius: 8px;
						box-shadow: 0 4px 12px rgba(0,0,0,0.08);
					}
					.header {
						padding: 1.5rem 2rem;
						background-color: #007bff;
						color: white;
						border-top-left-radius: 8px;
						border-top-right-radius: 8px;
					}
                    .header h1 {
                        margin: 0;
                        font-size: 1.8rem;
                    }
					table {
						width: 100%;
						border-collapse: collapse;
					}
					th, td {
						padding: 1rem 2rem;
						text-align: left;
						border-bottom: 1px solid #eee;
					}
					th {
						background-color: #f1f3f5;
						font-weight: 600;
					}
					a {
						color: #007bff;
						text-decoration: none;
					}
					a:hover {
						text-decoration: underline;
					}
				</style>
			</head>
			<body>
				<div id="sitemap">
					<div class="header">
						<h1>XML Sitemap</h1>
						<p>This sitemap is generated by Next.js for search engines like Google.</p>
					</div>
					<table>
						<thead>
							<tr>
								<th>URL</th>
								<th>Last Modified</th>
							</tr>
						</thead>
						<tbody>
							<xsl:for-each select="sitemap:urlset/sitemap:url">
								<tr>
									<td>
										<xsl:variable name="itemURL">
											<xsl:value-of select="sitemap:loc"/>
										</xsl:variable>
										<a href="{$itemURL}">
											<xsl:value-of select="sitemap:loc"/>
										</a>
									</td>
									<td>
										<xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,8)))"/>
									</td>
								</tr>
							</xsl:for-each>
						</tbody>
					</table>
				</div>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>